/**
 * @fileoverview EcoPulse AI — Assessment Celebration Summary.
 * Animated celebration view shown after completing all 8 assessment steps,
 * with confetti, estimated footprint preview, and summary chips.
 */

import React, { useMemo } from 'react';
import { Box, Typography, Button, useTheme, alpha } from '@mui/material';
import { Celebration } from '@mui/icons-material';
import { motion } from 'framer-motion';
import { useAssessmentStore } from '../../stores/appStore';
import { staggerContainer, staggerItem } from '../../theme/animations';
import { palette } from '../../theme/theme';
import { STEP_META } from './constants';

/** Pre-generated confetti particles — created at module scope to avoid impure Math.random() calls during render. */
const CONFETTI_PARTICLES = Array.from({ length: 30 }, (_, i) => ({
  id: i,
  x: Math.random() * 100,
  delay: Math.random() * 1.5,
  duration: 2 + Math.random() * 2,
  emoji: ['🌱', '🌿', '🍃', '💚', '✨', '🌍'][Math.floor(Math.random() * 6)],
  size: 14 + Math.random() * 14,
}));

/** Rough fuel factor map for quick preview estimate. */
const FUEL_FACTORS: Record<string, number> = {
  car_petrol: 0.21,
  car_diesel: 0.19,
  car_hybrid: 0.12,
  car_ev: 0.05,
  motorcycle: 0.11,
  bicycle: 0,
  walk: 0,
  none: 0,
};

/** Rough diet factor map for quick preview estimate (kg CO₂e/year). */
const DIET_FACTORS: Record<string, number> = {
  vegan: 1500,
  vegetarian: 1700,
  mixed: 2500,
  meat_heavy: 3300,
};

/** Props for the CelebrationSummary component. */
interface CelebrationSummaryProps {
  /** Callback when user clicks "See My Full Report". */
  onComplete: () => void;
}

/** Celebration view with confetti, estimated footprint, and summary. */
export default function CelebrationSummary({ onComplete }: CelebrationSummaryProps): React.JSX.Element {
  const theme = useTheme();
  const assessment = useAssessmentStore((s) => s.assessment);

  // Lightweight estimate for preview (actual report is generated by the engine)
  const estimatedTonnes = useMemo(() => {
    let total = 0;
    total += assessment.transportation.commuteDistanceKm * 365 * (FUEL_FACTORS[assessment.transportation.vehicleType] || 0.15);
    total += DIET_FACTORS[assessment.diet.dietType] || 2500;
    total += (assessment.electricity.monthlyBillUSD / 100) * 4000;
    total += assessment.travel.domesticFlightsPerYear * 250 + assessment.travel.internationalFlightsPerYear * 1200;
    return (total / 1000).toFixed(1);
  }, [assessment]);

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ type: 'spring', stiffness: 200, damping: 20 }}
      style={{ textAlign: 'center', position: 'relative', overflow: 'hidden' }}
    >
      {/* Confetti particles */}
      {CONFETTI_PARTICLES.map((p) => (
        <motion.div
          key={p.id}
          initial={{ y: -40, x: `${p.x}%`, opacity: 0, scale: 0 }}
          animate={{
            y: ['-10%', '110%'],
            opacity: [0, 1, 1, 0],
            scale: [0, 1, 1, 0.5],
            rotate: [0, 360],
          }}
          transition={{
            duration: p.duration,
            delay: p.delay,
            repeat: Infinity,
            repeatDelay: 1,
          }}
          style={{
            position: 'absolute',
            left: `${p.x}%`,
            fontSize: p.size,
            pointerEvents: 'none',
            zIndex: 0,
          }}
        >
          {p.emoji}
        </motion.div>
      ))}

      <Box sx={{ position: 'relative', zIndex: 1 }}>
        <motion.div
          animate={{ rotate: [0, 10, -10, 10, 0], scale: [1, 1.15, 1] }}
          transition={{ duration: 1.5, delay: 0.3 }}
        >
          <Typography sx={{ fontSize: '4rem', mb: 1 }}>🎉</Typography>
        </motion.div>

        <Typography variant="h4" sx={{ fontWeight: 800, mb: 1 }}>
          Assessment Complete!
        </Typography>
        <Typography variant="body1" sx={{ color: theme.palette.text.secondary, mb: 4, maxWidth: 400, mx: 'auto' }}>
          Great job! We've gathered everything we need to calculate your carbon footprint.
        </Typography>

        {/* Estimated footprint preview */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5, duration: 0.6 }}
        >
          <Box
            sx={{
              display: 'inline-flex',
              flexDirection: 'column',
              alignItems: 'center',
              px: 5,
              py: 3,
              borderRadius: 4,
              background: `linear-gradient(145deg, ${alpha(palette.emerald, 0.1)}, ${alpha(palette.mintGreen, 0.05)})`,
              border: `2px solid ${alpha(palette.emerald, 0.2)}`,
              boxShadow: `0 8px 32px ${alpha(palette.emerald, 0.15)}`,
              mb: 4,
            }}
          >
            <Typography variant="body2" sx={{ fontWeight: 600, color: theme.palette.text.secondary, mb: 0.5 }}>
              Estimated Annual Footprint
            </Typography>
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ type: 'spring', stiffness: 200, delay: 0.8 }}
            >
              <Typography
                variant="h2"
                sx={{
                  fontWeight: 900,
                  background: `linear-gradient(135deg, ${palette.emerald}, ${palette.skyBlue})`,
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                }}
              >
                ~{estimatedTonnes}
              </Typography>
            </motion.div>
            <Typography variant="body2" sx={{ fontWeight: 500, color: theme.palette.text.secondary }}>
              tonnes CO₂e / year
            </Typography>
            <Typography
              variant="caption"
              sx={{
                display: 'block',
                mt: 1.5,
                color: theme.palette.text.secondary,
                opacity: 0.7,
                fontStyle: 'italic',
                maxWidth: 320,
              }}
            >
              ℹ️ Estimates are based on EPA, IPCC AR6 &amp; DEFRA 2023 emission factors
              and are approximations for awareness purposes.
            </Typography>
          </Box>
        </motion.div>

        {/* Summary chips */}
        <motion.div
          variants={staggerContainer}
          initial="initial"
          animate="animate"
        >
          <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1, justifyContent: 'center', mb: 4 }}>
            {[
              { emoji: STEP_META[0].emoji, label: assessment.transportation.vehicleType.replace(/_/g, ' ') },
              { emoji: STEP_META[1].emoji, label: assessment.diet.dietType },
              { emoji: STEP_META[2].emoji, label: `$${assessment.electricity.monthlyBillUSD}/mo` },
              { emoji: STEP_META[6].emoji, label: `${assessment.travel.domesticFlightsPerYear + assessment.travel.internationalFlightsPerYear} flights/yr` },
            ].map((item, i) => (
              <motion.div key={i} variants={staggerItem}>
                <Box
                  sx={{
                    px: 2,
                    py: 0.8,
                    borderRadius: 3,
                    background: alpha(theme.palette.text.secondary, 0.06),
                    fontSize: '0.8rem',
                    fontWeight: 500,
                  }}
                >
                  {item.emoji} {item.label}
                </Box>
              </motion.div>
            ))}
          </Box>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 1.2 }}
        >
          <Button
            id="assessment-complete-btn"
            variant="contained"
            size="large"
            onClick={onComplete}
            startIcon={<Celebration />}
            sx={{
              px: 5,
              py: 1.6,
              fontSize: '1rem',
              fontWeight: 700,
              borderRadius: 3,
              background: `linear-gradient(135deg, ${palette.emerald}, ${palette.mintGreen})`,
              boxShadow: `0 8px 24px ${alpha(palette.emerald, 0.35)}`,
              '&:hover': {
                background: `linear-gradient(135deg, ${palette.forestGreen}, ${palette.emerald})`,
                boxShadow: `0 12px 32px ${alpha(palette.emerald, 0.4)}`,
                transform: 'translateY(-2px)',
              },
              transition: 'all 0.3s ease',
            }}
          >
            See My Full Report
          </Button>
        </motion.div>
      </Box>
    </motion.div>
  );
}
