/**
 * @fileoverview EcoPulse AI — Resources Page.
 * Educational content and sustainability learning hub.
 */

import { useState } from 'react';
import { motion } from 'framer-motion';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Chip from '@mui/material/Chip';
import Grid from '@mui/material/Grid';
import Collapse from '@mui/material/Collapse';
import IconButton from '@mui/material/IconButton';
import { alpha, useTheme } from '@mui/material/styles';
import ExpandMoreRoundedIcon from '@mui/icons-material/ExpandMoreRounded';
import { staggerContainer, staggerItem } from '../theme/animations';

interface Resource {
  id: string;
  title: string;
  icon: string;
  category: string;
  summary: string;
  details: string[];
  source: string;
}

const RESOURCES: Resource[] = [
  {
    id: 'carbon-footprint-101',
    title: 'What is a Carbon Footprint?',
    icon: '👣',
    category: 'Basics',
    summary: 'Your carbon footprint is the total amount of greenhouse gases generated by your actions, measured in CO₂ equivalents.',
    details: [
      'The average global carbon footprint is about 4.8 tonnes CO₂e per person per year.',
      'Transportation, food, and energy consumption are typically the largest contributors.',
      'The Paris Agreement target aims for under 2 tonnes per person by 2050.',
      'Even small lifestyle changes can create meaningful reductions over time.',
    ],
    source: 'IPCC AR6, EPA',
  },
  {
    id: 'food-impact',
    title: 'Food & Diet Impact',
    icon: '🥗',
    category: 'Deep Dive',
    summary: 'Food production is responsible for roughly 26% of global greenhouse gas emissions.',
    details: [
      'Beef production generates 60 kg CO₂e per kg — 10x more than chicken.',
      'A vegan diet can reduce food-related emissions by up to 73%.',
      'Food waste accounts for 8-10% of global emissions.',
      'Buying local reduces transportation emissions but production methods matter more.',
      'Seasonal eating reduces the energy needed for greenhouse growing and long-distance transport.',
    ],
    source: 'Poore & Nemecek (2018), Science',
  },
  {
    id: 'transport-guide',
    title: 'Transportation Choices',
    icon: '🚗',
    category: 'Deep Dive',
    summary: 'Transportation accounts for about 27% of emissions. Your commute and travel choices have significant impact.',
    details: [
      'A single transatlantic flight emits about 1.6 tonnes CO₂e per passenger.',
      'Electric vehicles produce 50-70% fewer emissions than petrol cars over their lifetime.',
      'Cycling for trips under 5 km saves about 0.5 kg CO₂e per trip compared to driving.',
      'Public transit produces about 50% fewer emissions per passenger-km than private cars.',
      'Working from home 2 days/week can save ~500 kg CO₂e annually from reduced commuting.',
    ],
    source: 'IEA, DEFRA 2023',
  },
  {
    id: 'home-energy',
    title: 'Home Energy Efficiency',
    icon: '🏠',
    category: 'Tips',
    summary: 'Home energy use is a major contributor. Simple efficiency improvements can reduce both emissions and bills.',
    details: [
      'LED bulbs use 75% less energy and last 25 times longer than incandescent bulbs.',
      'Adjusting your thermostat by just 1°C can reduce heating bills by 10%.',
      'Standby power ("phantom load") can account for 5-10% of household electricity.',
      'Energy-efficient appliances (A+++ rated) use up to 50% less energy.',
      'Proper insulation can reduce heating and cooling energy needs by up to 30%.',
    ],
    source: 'US DOE, Energy Star',
  },
  {
    id: 'waste-recycling',
    title: 'Waste Reduction & Recycling',
    icon: '♻️',
    category: 'Tips',
    summary: 'Waste management contributes 3-5% of global emissions. Reducing, reusing, and recycling all help.',
    details: [
      'Recycling aluminum saves 95% of the energy needed to make new aluminum.',
      'Composting food waste prevents methane emissions — 25x more potent than CO₂.',
      'The average person generates about 500 kg of waste per year.',
      'Reducing consumption is more impactful than recycling — the waste hierarchy matters.',
      'Textile recycling can save 3-4 kg CO₂e per kg of clothing diverted from landfill.',
    ],
    source: 'EPA, WRAP UK',
  },
  {
    id: 'water-climate',
    title: 'Water and Climate Connection',
    icon: '💧',
    category: 'Basics',
    summary: 'Water treatment and heating require significant energy. Conserving water reduces your carbon footprint.',
    details: [
      'Heating water accounts for about 17% of home energy use.',
      'A 5-minute shower uses about 40 liters of water vs. 150 liters for a bath.',
      'Cold water laundry saves 90% of the energy used per load.',
      'Fixing a dripping faucet can save over 11,000 liters of water per year.',
      'Water-efficient appliances reduce both water and energy consumption.',
    ],
    source: 'Water Footprint Network',
  },
  {
    id: 'methodology',
    title: 'Our Calculation Methodology',
    icon: '🔬',
    category: 'Transparency',
    summary: 'EcoPulse AI uses evidence-based emission factors from leading scientific sources to estimate your footprint.',
    details: [
      'Emission factors sourced from EPA, IPCC AR6, DEFRA 2023, and IEA.',
      'All values expressed in kg CO₂ equivalent (CO₂e), accounting for multiple greenhouse gases.',
      'Calculations are estimates based on average values — individual results may vary.',
      'We use activity-based methodology: your behaviors multiplied by emission factors.',
      'Our engine is open and configurable — emission factors can be updated as better data emerges.',
      'We clearly label all outputs as estimates, not precise measurements.',
    ],
    source: 'EcoPulse AI Team',
  },
  {
    id: 'getting-started',
    title: 'Getting Started with Sustainability',
    icon: '🌱',
    category: 'Guide',
    summary: 'Feeling overwhelmed? Start here. Small, consistent actions create real change over time.',
    details: [
      'Step 1: Complete your carbon footprint assessment to understand your baseline.',
      'Step 2: Identify your top 1-2 impact categories (usually transport or food).',
      'Step 3: Pick ONE easy recommendation to start with this week.',
      'Step 4: Build consistency before adding more changes.',
      'Step 5: Track your progress and celebrate small wins.',
      'Remember: Progress over perfection. Every action matters!',
    ],
    source: 'EcoPulse AI',
  },
];

const CATEGORIES = ['All', 'Basics', 'Deep Dive', 'Tips', 'Guide', 'Transparency'];

/** Resources page with filterable sustainability learning resources and expandable detail cards. */
export default function ResourcesPage() {
  const theme = useTheme();
  const [selectedCategory, setSelectedCategory] = useState('All');
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const filtered =
    selectedCategory === 'All'
      ? RESOURCES
      : RESOURCES.filter((r) => r.category === selectedCategory);

  return (
    <Box>
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <Typography
          variant="h3"
          sx={{
            fontWeight: 900,
            mb: 1,
            fontSize: { xs: '1.8rem', md: '2.5rem' },
            letterSpacing: '-0.02em',
          }}
        >
          Resources & Learning
        </Typography>
        <Typography
          variant="body1"
          sx={{ color: theme.palette.text.secondary, mb: 4, maxWidth: 600, lineHeight: 1.7 }}
        >
          Evidence-based guides to help you understand sustainability and make informed choices.
        </Typography>
      </motion.div>

      {/* Category Filters */}
      <Box sx={{ display: 'flex', gap: 1, mb: 4, flexWrap: 'wrap' }}>
        {CATEGORIES.map((cat) => (
          <Chip
            key={cat}
            label={cat}
            onClick={() => setSelectedCategory(cat)}
            id={`resource-filter-${cat.toLowerCase().replace(/\s/g, '-')}`}
            variant={selectedCategory === cat ? 'filled' : 'outlined'}
            sx={{
              fontWeight: 600,
              borderRadius: 3,
              ...(selectedCategory === cat
                ? {
                    background: `linear-gradient(135deg, ${theme.palette.primary.main}, ${theme.palette.primary.light})`,
                    color: '#fff',
                    boxShadow: `0 4px 12px ${alpha(theme.palette.primary.main, 0.3)}`,
                  }
                : {
                    borderColor: alpha(theme.palette.primary.main, 0.2),
                    '&:hover': { background: alpha(theme.palette.primary.main, 0.06) },
                  }),
            }}
          />
        ))}
      </Box>

      {/* Resource Cards */}
      <motion.div variants={staggerContainer} initial="initial" animate="animate">
        <Grid container spacing={2.5}>
          {filtered.map((resource) => (
            <Grid size={{ xs: 12, md: 6 }} key={resource.id}>
              <motion.div variants={staggerItem}>
                <Card
                  sx={{
                    cursor: 'pointer',
                    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
                    '&:hover': {
                      transform: 'translateY(-4px)',
                      boxShadow: `0 12px 36px ${alpha(theme.palette.primary.main, 0.1)}`,
                    },
                  }}
                  onClick={() => setExpandedId(expandedId === resource.id ? null : resource.id)}
                >
                  <CardContent sx={{ p: 3 }}>
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                      <Box sx={{ display: 'flex', gap: 2, alignItems: 'flex-start', flex: 1 }}>
                        <Box
                          sx={{
                            width: 52,
                            height: 52,
                            borderRadius: 3,
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            fontSize: 28,
                            background: alpha(theme.palette.primary.main, 0.08),
                            flexShrink: 0,
                          }}
                        >
                          {resource.icon}
                        </Box>
                        <Box>
                          <Chip
                            label={resource.category}
                            size="small"
                            sx={{
                              mb: 1,
                              fontSize: '0.7rem',
                              fontWeight: 600,
                              background: alpha(theme.palette.secondary.main, 0.1),
                              color: theme.palette.secondary.dark,
                            }}
                          />
                          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 0.5 }}>
                            {resource.title}
                          </Typography>
                          <Typography variant="body2" sx={{ color: theme.palette.text.secondary, lineHeight: 1.6 }}>
                            {resource.summary}
                          </Typography>
                        </Box>
                      </Box>

                      <IconButton
                        size="small"
                        aria-label={expandedId === resource.id ? 'Collapse' : 'Expand'}
                        onClick={(e) => { e.stopPropagation(); setExpandedId(expandedId === resource.id ? null : resource.id); }}
                        sx={{
                          transform: expandedId === resource.id ? 'rotate(180deg)' : 'rotate(0)',
                          transition: 'transform 0.3s',
                        }}
                      >
                        <ExpandMoreRoundedIcon />
                      </IconButton>
                    </Box>

                    {/* Expanded details */}
                    <Collapse in={expandedId === resource.id}>
                      <Box
                        sx={{
                          mt: 2,
                          pt: 2,
                          borderTop: `1px solid ${alpha(theme.palette.primary.main, 0.08)}`,
                        }}
                      >
                        {resource.details.map((detail, i) => (
                          <Box
                            key={i}
                            sx={{
                              display: 'flex',
                              gap: 1.5,
                              mb: 1.2,
                              alignItems: 'flex-start',
                            }}
                          >
                            <Box
                              sx={{
                                width: 6,
                                height: 6,
                                borderRadius: '50%',
                                background: theme.palette.primary.main,
                                mt: 0.8,
                                flexShrink: 0,
                              }}
                            />
                            <Typography variant="body2" sx={{ lineHeight: 1.6, color: theme.palette.text.secondary }}>
                              {detail}
                            </Typography>
                          </Box>
                        ))}
                        <Typography
                          variant="caption"
                          sx={{
                            display: 'block',
                            mt: 1.5,
                            color: alpha(theme.palette.text.secondary, 0.7),
                            fontStyle: 'italic',
                          }}
                        >
                          Source: {resource.source}
                        </Typography>
                      </Box>
                    </Collapse>
                  </CardContent>
                </Card>
              </motion.div>
            </Grid>
          ))}
        </Grid>
      </motion.div>

      {/* Disclaimer */}
      <Box
        sx={{
          mt: 6,
          p: 3,
          borderRadius: 4,
          background: alpha(theme.palette.info.main, 0.06),
          border: `1px solid ${alpha(theme.palette.info.main, 0.12)}`,
        }}
      >
        <Typography variant="body2" sx={{ color: theme.palette.text.secondary, lineHeight: 1.7 }}>
          📝 <strong>Disclaimer:</strong> Carbon estimates are approximations based on available data and scientific
          emission factors. Individual results may vary. EcoPulse AI aims to provide directional guidance for
          sustainable living, not precise measurements. All sources are cited for transparency.
        </Typography>
      </Box>
    </Box>
  );
}
